### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by MercyfulFate**
Fixed a bug with refuel on remote _vehicles.
You can now only have a single full OR empty jerrycan.

### CODE REVIEW

**Comment by JoSchaap** [comment]
thanks

**Comment by JoSchaap** [comment]
still doesnt show the respawn dialog and spams out alot of errors :(

**Comment by MercyfulFate** [comment]
hmmm... Thats interesting. I'll look into it once I get home.
do those errors only come up when running on a dedicated server?
are you running with "DEBUG= true" or false in the missions init.sqf?
I ran this on both the standard branch and development branch and had no issues :/.

Just as a side note, if your running this on a server, DEBUG should be set to "false", otherwise it will recompile the function everytime its called, rather than using compileFinal.

**Comment by MercyfulFate** [comment]
I've had a look running it in the arma 3 dev branch and all seems to run fine.
That first error message looks like the mf_init function doesn't exist, however its explicitly defined in the base init.sqf file, so not sure whats happened. Can you make sure that your base init.sqf file is the same as the repo. if the function "mf_init" and "mf_compile" are not in there, then that would explain all the errors.

**Pull request merged**
