### PR TITLE
Inventory

### PR DESCRIPTION
**Pull request by MercyfulFate**
Inventory Added.
- Canned Food
- Water
- Jerrycan (full and empty)
- Medkits
- Repair Kits
- Camo Net

Spawn Beacons Added and Working

### CODE REVIEW

**Comment by MercyfulFate** [comment]
Rebased on the lastest TESTING_23 commit

**Comment by MercyfulFate** [comment]
found an issue with the refuel.
I've got the fix ready for a pull-request once you merge this one.

**Comment by JoSchaap** [comment]
will merge this in a second. medkits will be removed. we allready have medics and medkits in the regular inventory :)
i cant find the 'pickup camonet/study improvised roof' code anywhere. i might just be missing something :+1: 

ill create a backupbranch before merging this :)

**Comment by MercyfulFate** [comment]
its under camonet in "clients/items". I called it pack/unpack as it made more sense than "study"

**Pull request merged**
