### PR TITLE
Initial commit of GoT Wasteland v2

### PR DESCRIPTION
**Pull request by JoSchaap**
Need to test this, but will likely be ok.
Once merged into the master branch this is final :)

+changelog for v2:
+
-    [Added] 8 new towns/settlements to spawn in.
-    [Added] 16 new spawnareas for objects/vehicles.
-    [Added] 3 new fuelpump locations
-    [Added] new underwater sidemission!
-    [Added] new scuba Mainmission with armed boat
-    [Added] Diving goggles/gear to gunstore.
-    [Added] Game info, hints and tips to briefing
-    [Added] Ghilly suits, Rangefinder to gunstore
-    [Added] Sniper Rifles and ammo to gunstore
-    [Added] SOS Sniper optic to gunstore
-    [Added] Random boat spawns near coastlines
-    [Added] new gunstore to even the odds
-    [Added] some scriptdetection
-    [Added] gunstore option to sell uniform/vest
-    [Added] New basebuilding parts
-    [Added] Explosive specialist class
-    [Fixed] Cleanup on corpse food/water/money
-    [Changed] Marksman class to Sniper class
-    [Changed] Sniper class spawns in ghillie
-    [Changed] Explosive Spec. needs toolkit to defuse
-    [Changed] Gunstore radar radius reduced to 70 ft
-    [Changed] Gunstore locations.
-    [Changed] Prices on MXM, EBR and Diving equipment.
-    [Changed] Reduced ammount of objects
-    [Changed] Reduced ammount of ammo caches
-    [Changed] Civilian boats respawn faster
-    [Changed] Rubber boats are movable by players
-    [Changed] Rubber boats respawn faster
-    [Changed] Armed boats are heli-liftable
-    [Changed] Armed boats have storage space

### CODE REVIEW

**Comment by killernetworkgaming** [comment]
Hello m8 how easy would it be to add a whitelist option basicly no access to the server unless ur id has been whitelisted could be done along the same lines as the admin panel just if ur id is not added to whitelist page the server auto kicks would get rid of hackers plus very easy to police no id no access

**Comment by killernetworkgaming** [comment]
Also ifrit's would be better if u could airlift them loaded with men then you could drop a fully manned up ifrit into a battle area ready to go great for supprise attacks on gun stores

**Comment by JoSchaap** [comment]
i think this is more of an idea for a seperate serverside addon/mod rather then something you want to put into the mission.

easyest way for now is to use a passworded server.

as for toving full vehicles. i know domination allows it but what would prevent you from lifting an enemy vehicle full of players and dump it in the ocean? :)

**Comment by JoSchaap** [comment]
currently known issues are here: https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/issues

**Pull request merged**
